server:
  port: 8080
spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.0.108:3306/guli?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yangchun0302.
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  profiles:
    active: dev

#logging:
#  level:
#    root: warn
#    com.yangchun.yangdemo: debug

#  configuration:
#    log-impl=org:
#      apache:
#        ibatis:
#          logging:
#            stdout:
#              StdOutImpl:
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:dao/xml/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.yangchun.yangdemo  # 注意：对应实体类的路径
#  configuration:
#    log-impl=org:
#      apache:
#        ibatis:
#          logging:
#            stdout:
#              StdOutImpl:
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql